name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint
        env:
          CI: true

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - run: npm ci
      - run: npm run build
      - run: npx jest --maxWorkers 2 --coverage
        env:
          CI: true
      - if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Lua Install
        run: sudo apt-get install lua5.3 luajit
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - run: npm ci
      - run: npm run build
      # This will never result in a direct cache hit.
      # Teherefore benchmark data is always updated.
      - name: Cache benchmark data
        id: cache-benchmark
        uses: actions/cache@v1
        with:
          path: ./benchmark/data
          key: ${{ runner.os }}-master-benchmark-${{ github.sha }}
          restore-keys: ${{ runner.os }}-master-benchmark-
      - name: Ensure benchmark data dir exists
        run: mkdir -p ./benchmark/data
      - name: Build benchmark Lua 5.3
        run: node ../dist/tstl.js -p tsconfig.53.json
        working-directory: benchmark
      - name: Run benchmark Lua 5.3
        id: benchmark-lua
        run: echo ::set-output name=info::`lua5.3 -- run.lua ../data/benchmark_master_53.json ${{github.ref}}`
        working-directory: benchmark/dist
      - name: Build benchmark LuaJIT
        run: node ../dist/tstl.js -p tsconfig.jit.json
        working-directory: benchmark
      - name: Run benchmark LuaJIT
        id: benchmark-jit
        run: echo ::set-output name=info::`luajit -- run.lua ../data/benchmark_master_jit.json ${{github.ref}}`
        working-directory: benchmark/dist
      - name: Create benchmark check
        uses: actions/github-script@0.9.0
        with:
          benchmark-info-lua: ${{steps.benchmark-lua.outputs.info}}
          benchmark-info-jit: ${{steps.benchmark-jit.outputs.info}}
          script: |
            const benchmarkInfoLua = JSON.parse(core.getInput('benchmark-info-lua', { required: true }));
            const benchmarkInfoJIT = JSON.parse(core.getInput('benchmark-info-jit', { required: true }));

            const summary = `### Lua5.3\n${benchmarkInfoLua.summary}\n### LuaJIT\n${benchmarkInfoJIT.summary}`;

            const text = `### Lua5.3\n${benchmarkInfoLua.text}\n### LuaJIT\n${benchmarkInfoJIT.text}`;

            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Benchmark results",
              head_sha: context.sha,
              status: "completed",
              conclusion: "neutral",
              output: {
                title: "Benchmark results",
                summary: summary,
                text: text
              }
            });
