name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install --global npm@6
      - run: npm ci
      - run: npm run lint
        env:
          CI: true

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 8.5.0
        uses: actions/setup-node@v1
        with:
          node-version: 8.5.0
      - run: npm install --global npm@6
      - run: npm ci
      - run: npm run build
      - run: npx jest --coverage
        env:
          CI: true
      - if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
